---
title: "data_wrangling"
author: "Sunny Siddique"
date: "September 18, 2018"
output: html_document
---

```{r}
library(tidyverse)
```

## import fas csv file

Import my first csv.

```{r}
pups_data = read_csv("./data/FAS_pups.csv")
litters_data = read_csv("./data/FAS_litters.csv")
```

```{r}
pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

select (pups_data, litter_number, sex, pd_ears)
```



## Filter Observations

Do some filtering

```{r}
filter(pups_data, sex == 1, pd_walk < 11)
```


Create variable
```{r}
mutate(litters_data,
       wt_gain = gd18_weight - gd0_weight,
       group = tolower(group)
       )
```

##Piping

Look at intermediate object approach:

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)
litters_data_with_vars = mutate(litters_data_selected_cols, 
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group))
litters_data_with_vars
```

Use nested function calls:

```{r}
litters_data_clean = 
  mutate(
    select(
      janitor::clean_names(
        read_csv("./data/FAS_litters.csv", col_types = "ccddiiii")
        ), 
    -pups_survive
    ),
  wt_gain = gd18_weight - gd0_weight,
  group = tolower(group)
  )
litters_data_clean
```

Use piping

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group))

litters_data
```



























